### create customer
POST http://localhost:8080/customer/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTQU5EUk9fREVWIiwiaWF0IjoxNjkxMzU3OTE3LCJzdWIiOiI1IiwiYXVkIjoiQ1VTVE9NRVJfTUFOQUdFTUVOVF9TRVJWSUNFIiwiZXhwIjoxNjkxNDQ0MzE3LCJhdXRob3JpdGllcyI6WyJSRUFEOlVTRVIiLCJSRUFEOkNVU1RPTUVSIiwiQ1JFQVRFOlVTRVIiLCJDUkVBVEU6Q1VTVE9NRVIiLCJVUERBVEU6VVNFUiIsIlVQREFURTpDVVNUT01FUiIsIkRFTEVURTpVU0VSIiwiREVMRVRFOkNVU1RPTUVSIl19.xkyrw5o05wjVueOXO_IPjIkTsb7KaqdP6H4DOVa60fVqw_74B8NVXq4PjycQcrJucZ7HVz10_2teZKKY9tD9mQ

{
  "firstName": "Harry",
  "lastName": "Potato",
  "email": "harry@potato.us",
  "status": "ACTIVE",
  "phone": "11119090",
  "address": "Wayward Road 23, Minneapolis",
  "type": "INDIVIDUAL",
  "imageUrl": "image"
}

### list of customers
GET http://localhost:8080/customer/list
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTQU5EUk9fREVWIiwiaWF0IjoxNjkxMzU3OTE3LCJzdWIiOiI1IiwiYXVkIjoiQ1VTVE9NRVJfTUFOQUdFTUVOVF9TRVJWSUNFIiwiZXhwIjoxNjkxNDQ0MzE3LCJhdXRob3JpdGllcyI6WyJSRUFEOlVTRVIiLCJSRUFEOkNVU1RPTUVSIiwiQ1JFQVRFOlVTRVIiLCJDUkVBVEU6Q1VTVE9NRVIiLCJVUERBVEU6VVNFUiIsIlVQREFURTpDVVNUT01FUiIsIkRFTEVURTpVU0VSIiwiREVMRVRFOkNVU1RPTUVSIl19.xkyrw5o05wjVueOXO_IPjIkTsb7KaqdP6H4DOVa60fVqw_74B8NVXq4PjycQcrJucZ7HVz10_2teZKKY9tD9mQ
