# Database
DB_USERNAME: root
DB_PASSWORD: root
DB_HOST: localhost
DB_PORT: 3306
DB_NAME: securecapita

# Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: test

# Email
EMAIL_HOST: smtp-mail.outlook.com
EMAIL_PORT: 587
EMAIL_USERNAME: formicale@hotmail.com
EMAIL_PASSWORD: umSs_77_wiFa_77_!
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200

JWT_SECRET: questoragazzodellaviaglucksidivertivaagiocareconme

